#!/usr/bin/env bash
# scripts/build-ppa.sh — produce Launchpad-uploadable source packages.
#
# Usage:
#   scripts/build-ppa.sh                       # build for whatever series
#                                              # is already in debian/changelog
#   scripts/build-ppa.sh noble                 # build once for noble
#   scripts/build-ppa.sh noble questing resolute
#                                              # build a separate source
#                                              # package per series
#
# Per-series counter is auto-incremented: if the changelog already has
# 0.2.0~noble2, the next noble build is stamped 0.2.0~noble3. This is
# what Launchpad requires for re-uploads (it rejects duplicate versions).
#
# Per-series Cargo.lock: if debian/lockfiles/<series>.lock exists, it's
# swapped in for that series's build. Generated by
# scripts/regen-series-lockfiles.sh. Series without an entry (resolute)
# use the canonical ./Cargo.lock.
#
# Supported series: questing, resolute. Noble (24.04) is NOT supported
# — cargo 1.75 can't parse the modern crates.io registry. Noble users
# build from source with rustup.
#
# After the build:
#   dput ppa:devtochukwu/clipd ../clipd_<version>_source.changes
#
# Launchpad builders run sbuild in a network-less chroot. Cargo crates
# cannot be fetched at build time, so we vendor them into ./vendor/
# locally and ship that directory inside the source tarball. The local
# .cargo/config.toml redirects cargo's crates-io source at the vendor
# tree.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# Optional: pass KEY=<fingerprint-or-uid> to override the signing key
# (e.g. when your Launchpad-registered GPG key has a different UID from
# the changelog's Maintainer line). KEY="" disables signing entirely —
# useful for local sanity-check builds, but the resulting source package
# is NOT uploadable to Launchpad.
SIGN_ARGS=()
if [ "${KEY+set}" = "set" ]; then
    if [ -z "${KEY}" ]; then
        SIGN_ARGS=(-us -uc)
        echo "==> KEY is empty — building unsigned (local test only)"
    else
        SIGN_ARGS=("-k${KEY}")
        echo "==> signing with key: $KEY"
    fi
fi

# Tool sanity-check before we touch anything.
for tool in dpkg-buildpackage dch dpkg-parsechangelog cargo; do
    if ! command -v "$tool" >/dev/null; then
        echo "error: $tool not installed."
        echo "       apt install devscripts dpkg-dev rustc cargo"
        exit 1
    fi
done

# --- helpers --------------------------------------------------------

# Pick the next free counter for a series. Looks at debian/changelog
# for existing entries matching `0.2.0~<series>N` and returns max(N)+1.
next_counter() {
    local upstream=$1 series=$2 max
    max=$(grep -oE "${upstream}~${series}[0-9]+" debian/changelog \
          | grep -oE '[0-9]+$' \
          | sort -n | tail -1)
    if [ -z "$max" ]; then
        echo 1
    else
        echo $((max + 1))
    fi
}

# Vendor crates + downgrade lockfile + build source package for the
# changelog's current top entry. Caller is responsible for stamping the
# changelog (single-series mode skips this; multi-series mode calls dch
# beforehand).
vendor_and_build() {
    local ver=$1 series=$2

    # Clear any stale .cargo/config.toml left over from a previous
    # series. The vendor stanza in there points cargo at vendor/, which
    # was populated for that other series's deps — if we leave it in
    # place, this run's `cargo vendor --locked` tries to find versions
    # that aren't in vendor/ and fails with "lockfile needs to be
    # updated". cargo vendor will rewrite this file on the next line.
    rm -f .cargo/config.toml

    # Swap in per-series lockfile if one exists. questing pulls from
    # debian/lockfiles/; resolute uses the canonical ./Cargo.lock.
    # We back up the canonical to a temp file (NOT to git) so the
    # restore at the end works regardless of whether the working tree
    # was already in sync with HEAD. The prior approach used
    # `git checkout -- Cargo.lock` and silently reverted local clean-ups
    # that hadn't been committed yet.
    local series_lock="debian/lockfiles/${series}.lock"
    local canonical_backup=""
    if [ -f "$series_lock" ]; then
        canonical_backup=$(mktemp --suffix=.Cargo.lock)
        cp Cargo.lock "$canonical_backup"
        echo "   using per-series lockfile: $series_lock"
        cp "$series_lock" Cargo.lock
    fi

    # Vendor the crates referenced by the (possibly swapped-in) lockfile.
    # `cargo vendor --locked` aborts if the lockfile is out of sync, so
    # this also serves as a sanity check.
    echo "   cargo vendor (Cargo.lock → vendor/)"
    mkdir -p .cargo
    cargo vendor --locked > .cargo/config.toml

    # Force lockfile to v3. noble's cargo 1.75 only reads v3
    # ("lock file version 4 requires -Znext-lockfile-bump"). v4 is
    # encoding-compatible for our dep graph, so the sed is safe.
    sed -i 's/^version = 4$/version = 3/' Cargo.lock

    echo "   dpkg-buildpackage -S for ${ver}"
    dpkg-buildpackage -S -sa -d "${SIGN_ARGS[@]}"

    # Restore the canonical Cargo.lock we stashed at the top of this
    # function, so the next series build starts from a known state.
    if [ -n "$canonical_backup" ]; then
        mv "$canonical_backup" Cargo.lock
    fi

    echo "   built ../clipd_${ver}_source.changes"
}

# --- single-series mode ---------------------------------------------

SERIES_LIST=("$@")
if [ "${#SERIES_LIST[@]}" -eq 0 ]; then
    cur_ver=$(dpkg-parsechangelog -S Version)
    cur_series=$(dpkg-parsechangelog -S Distribution)
    echo "==> single-series build: $cur_series ($cur_ver)"
    vendor_and_build "$cur_ver" "$cur_series"
    echo
    echo "Built. Upload with:"
    echo "   dput ppa:devtochukwu/clipd ../clipd_${cur_ver}_source.changes"
    exit 0
fi

# --- multi-series mode ----------------------------------------------

UPSTREAM_VERSION="$(dpkg-parsechangelog -S Version | sed 's/~.*//')"

declare -A BUILT_VERS
for series in "${SERIES_LIST[@]}"; do
    counter=$(next_counter "$UPSTREAM_VERSION" "$series")
    ver="${UPSTREAM_VERSION}~${series}${counter}"
    echo
    echo "==> series: $series → version $ver"

    # --force-bad-version: per-series versions don't form a single
    # monotonic sequence (~questing2 sorts < ~resolute2). dch otherwise
    # refuses to add an entry that goes "backwards".
    DEBEMAIL="ntmark2004@gmail.com" DEBFULLNAME="SimpleX-T" \
        dch --force-distribution --force-bad-version \
            --newversion "$ver" --distribution "$series" \
            "Build for $series."
    vendor_and_build "$ver" "$series"
    BUILT_VERS["$series"]="$ver"
done

echo
echo "All series built. Upload with:"
for series in "${SERIES_LIST[@]}"; do
    echo "   dput ppa:devtochukwu/clipd ../clipd_${BUILT_VERS[$series]}_source.changes"
done
